apiVersion: v1
kind: Service
metadata:
  name: redis 
  labels:
    app: redis
    favorite: gorlock
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379         # servicePort
      targetPort: 6379   # containerPort
  type: ClusterIP