apiVersion: batch/v1
kind: Job
metadata:
  name: voting-seed
spec:
  backoffLimit: 3                    # Retry up to 3 times if pod fails
  activeDeadlineSeconds: 300         # Kill job if it runs longer than 5 minutes
  ttlSecondsAfterFinished: 120       # Auto-delete job 2 minutes after completion
  completions: 1                     # Job succeeds when 1 pod completes successfully
  parallelism: 1                     # Run only 1 pod at a time
  template:
    spec:
      restartPolicy: Never           # Required for Jobs - don't restart failed pods
      containers:
      - name: seed
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Install required tools
          apk add --no-cache python3 curl apache2-utils
          
          # Download and run the Python script to create data files
          curl -o make-data.py https://raw.githubusercontent.com/dockersamples/example-voting-app/refs/heads/main/seed-data/make-data.py
          python3 make-data.py
          
          # Download and run the shell script
          curl -o generate-votes.sh https://raw.githubusercontent.com/aaron-dm-mcdonald/anton-basic-eks-updated/refs/heads/main/voting-app/seed/generate-votes.sh
          chmod +x generate-votes.sh
          
          # Run the voting script (now includes wait logic)
          ./generate-votes.sh
        env:
        - name: VOTE_SERVICE_URL
          value: "http://vote"