apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
    favorite: lizzo
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80         # servicePort
      targetPort: 80   # containerPort
  type: LoadBalancer

