apiVersion: v1
kind: Pod
metadata:
  name: db
  labels: 
    app: db
spec:
  containers:
  - name: db
    image: postgres:15-alpine
    ports:
    - containerPort: 5432
      name: postgres
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-volume
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
  volumes:
  - name: db-volume
    emptyDir: {}