apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    favorite: precious
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432        # servicePort
      targetPort: 5432   # containerPort
  type: ClusterIP